using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace EnumExtensions.Tool.Helpers;

internal static class AttributeExtensions
{
    public static void EnsureAttributeExists(string root)
    {
        var attrPath = Path.Combine(root, "GenerateEnumExtensionsAttribute.g.cs");

        if (File.Exists(attrPath))
            return;

        var code = """
// <auto-generated/>
using System;

[AttributeUsage(AttributeTargets.Enum)]
public sealed class GenerateEnumExtensionsAttribute : Attribute
{
}
""";

        File.WriteAllText(attrPath, code);
    }

    internal static bool HasGenerateAttribute(EnumDeclarationSyntax enumDecl)
    {
        foreach (var attrList in enumDecl.AttributeLists)
        {
            foreach (var attr in attrList.Attributes)
            {
                if (attr.Name is IdentifierNameSyntax ins &&
                     (ins.Identifier.Text is "GenerateEnumExtensions" or "GenerateEnumExtensionsAttribute"))
                    return true;
            }
        }

        return false;
    }
}
